config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "projects#index"
  resources :projects
  resources :page_views, only: [:index, :show]

  namespace :api do
    namespace :v1 do
      resources :page_views, only: :create
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page_view.rb
class PageView < ApplicationRecord
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :page_views, dependent: :destroy
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, unless: -> { request.format.json? }
end

app/controllers/api/v1/application_controller.rb
class Api::V1::ApplicationController < Api::ApplicationController
end

app/controllers/api/v1/page_views_controller.rb
class Api::V1::PageViewsController < Api::V1::ApplicationController
  def create
    view = project.page_views.build(permitted_params)
    if view.save
      render json: {}, status: :created
    else
      render json: view.errors, status: :error
    end
  end

  private

    def project
      @project ||= Project.find_by!(token: params.dig(:page_view, :project_token))
    end

    def permitted_params
      params.require(:page_view).permit(:path, :referrer, :title)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/page_views_controller.rb
class PageViewsController < ApplicationController
  before_action :set_page_view, only: [:show, :edit, :update, :destroy]

  # GET /page_views
  # GET /page_views.json
  def index
    @page_views = PageView.all
  end

  # GET /page_views/1
  # GET /page_views/1.json
  def show
  end

  # GET /page_views/new
  def new
    @page_view = PageView.new
  end

  # GET /page_views/1/edit
  def edit
  end

  # POST /page_views
  # POST /page_views.json
  def create
    @page_view = PageView.new(page_view_params)

    respond_to do |format|
      if @page_view.save
        format.html { redirect_to @page_view, notice: 'Page view was successfully created.' }
        format.json { render :show, status: :created, location: @page_view }
      else
        format.html { render :new }
        format.json { render json: @page_view.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /page_views/1
  # PATCH/PUT /page_views/1.json
  def update
    respond_to do |format|
      if @page_view.update(page_view_params)
        format.html { redirect_to @page_view, notice: 'Page view was successfully updated.' }
        format.json { render :show, status: :ok, location: @page_view }
      else
        format.html { render :edit }
        format.json { render json: @page_view.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /page_views/1
  # DELETE /page_views/1.json
  def destroy
    @page_view.destroy
    respond_to do |format|
      format.html { redirect_to page_views_url, notice: 'Page view was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page_view
      @page_view = PageView.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_view_params
      params.fetch(:page_view, {})
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  BOOSTRAP_CLASSES = {
    success: "alert-success",
    error: "alert-danger",
    alert: "alert-warning",
    notice: "alert-info"
  }.stringify_keys.freeze

  def bootstrap_class_for(flash_type)
    BOOSTRAP_CLASSES.fetch(flash_type.to_s) { flash_type.to_s }
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat flash_message(msg_type, message)
    end
    nil
  end

  def flash_message(msg_type, message)
    content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible fade show mt-2", role: "alert") do
      concat message
      concat content_tag(:button, close_alert, class: "close", data: { dismiss: 'alert' }, aria: { label: "Close" })
    end
  end

  def close_alert
    content_tag(:span, "&times;".html_safe, aria: { hidden: true })
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trackie</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">About</h4>
              <p class="text-muted"></p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <ul class="list-unstyled">
                <li><%= link_to "Projects", projects_path, class: "text-white" %></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href="/" class="navbar-brand d-flex align-items-center">
            <%= octicon(:project, height: 32, fill: "currentcolor", class: "mr-2") %>
            <strong>Trackie</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>
    <div class="container-fluid">
      <%= flash_messages %>
      <%= yield %>
      <div class="modal fade" id="app-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle"></h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/page_views/_form.html.erb
<%= form_with(model: page_view, local: true) do |form| %>
  <% if page_view.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page_view.errors.count, "error") %> prohibited this page_view from being saved:</h2>

      <ul>
      <% page_view.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/page_views/edit.html.erb
<h1>Editing Page View</h1>

<%= render 'form', page_view: @page_view %>

<%= link_to 'Show', @page_view %> |
<%= link_to 'Back', page_views_path %>

app/views/page_views/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Page Views</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @page_views.each do |page_view| %>
      <tr>
        <td><%= link_to 'Show', page_view %></td>
        <td><%= link_to 'Edit', edit_page_view_path(page_view) %></td>
        <td><%= link_to 'Destroy', page_view, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page View', new_page_view_path %>

app/views/page_views/new.html.erb
<h1>New Page View</h1>

<%= render 'form', page_view: @page_view %>

<%= link_to 'Back', page_views_path %>

app/views/page_views/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_page_view_path(@page_view) %> |
<%= link_to 'Back', page_views_path %>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>